# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://mitchjcarlson.github.io"

# Site title
# title = "site title"

# Copyright
copyright = "(c) 2016 Mitch Carlson."

# Language
languageCode = "en-EN"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "your_disqus_shortname"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    series = "series"

[author]
    name = "Mitch Carlson"
    email = "mitchjcarlson@gmail.com"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Logic Gate"
    topline = "Exploring data structures and algorithms, design patterns, coding practices, dev tools, libraries, personal projects, and many other things."
    footline = "I <i class='fa fa-heart'></i> code"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "mitchjcarlson" # Your Github profile ID
    bitbucket = "mitchjcarlson" # Your Bitbucket profile ID
    linkedin = "mitch-carlson-8b39103b" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "mitchjcarlson" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
